#pragma once

enum {

    Osurf = 5000,
    
    ID_GEOTIFF_DATA,

    GEOTIFF_FILE,
    GEOTIFF_UNITS,
    GEOTIFF_UNITS_METERS,
    GEOTIFF_UNITS_DEGREES,
    GEOTIFF_LAYER,
    GEOTIFF_NO_DATA,
    GEOTIFF_SHOW_COORDS,

    ID_GEOMESH_PROPERTIES,
    GEOMESH_TYPE,
    GEOMESH_TYPE_TRN,
    GEOMESH_TYPE_TIN,
    GEOMESH_STEP,
    GEOMESH_GLOBAL_SCALE,
    GEOMESH_MEASURE_SCALE,
    GEOMESH_VERTICAL_ALIGN,
    GEOMESH_VERTICAL_MIN_VALUE,
    GEOMESH_VERTICAL_MAX_VALUE,
    GEOMESH_VERTICAL_MEAN_VALUE,
    GEOMESH_VERTICAL_CENTER_VALUE,
    GEOMESH_VERTICAL_SOLID_BASE,
    GEOMESH_SOLID_BASE,
    GEOMESH_BASE_THICKNESS,
    GEOMESH_UVW,
    GEOMESH_UVW_TOP_VIEW,
    GEOMESH_UVW_HEIGHT,

    ID_GEOMESH_TIN_PROPERTIES,
    GEOMESH_TYPE_TIN_SEED,
    GEOMESH_GAUSSIAN_SAMPLING_THRESHOLD,
    GEOMESH_UNIFORM_SAMPLING_THRESHOLD,
    GEOMESH_GRADIENT_THRESHOLD,

    GEOMESH_GENERATE,
};